name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: login no docker resgistry
      uses: docker/login-action@v3.4.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    
    - name: construção da imagem docker 
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: |
          blackvsk/estudo-cicd:v${{github.run.number}}
          blackvsk/estudo-cicd:latest
      
